In [8]:
import pandas as pd


In [10]:
df=pd.read_csv('Employers_data.csv')

In [13]:
df.head(10)

Employee_ID               Name  Age  Gender   Department  Job_Title  \
0            1       Merle Ingram   24  Female  Engineering   Engineer   
1            2         John Mayes   56    Male        Sales  Executive   
2            3       Carlos Wille   21    Male  Engineering     Intern   
3            4     Michael Bryant   30    Male      Finance    Analyst   
4            5      Paula Douglas   25  Female           HR    Analyst   
5            6     Michael Irving   35    Male      Finance    Manager   
6            7  Marcelle Campbell   23  Female    Marketing    Analyst   
7            8        Glenda Leal   47  Female    Marketing    Manager   
8            9    Walter Williams   43    Male    Marketing    Manager   
9           10     Vanessa Songer   23  Female    Marketing    Analyst   

   Experience_Years Education_Level       Location  Salary  
0                 1          Master         Austin   90000  
1                33          Master        Seattle  195000  
2                 1        Bachelor       New York   35000  
3                 9        Bachelor       New York   75000  
4                 2          Master        Seattle   70000  
5                 8             PhD       New York  125000  
6                 2        Bachelor  San Francisco   60000  
7                24          Master  San Francisco  145000  
8                16             PhD  San Francisco  135000  
9                 0          Master  San Francisco   70000

In [14]:
df.tail(20)

Employee_ID                  Name  Age  Gender   Department  Job_Title  \
9980         9981      Carroll Cummings   22    Male  Engineering     Intern   
9981         9982        Gary Magdaleno   30    Male      Finance    Analyst   
9982         9983         Robert Wyrick   33    Male      Product    Manager   
9983         9984  Stanley Bialaszewski   23    Male           HR    Analyst   
9984         9985         Florence Rose   46  Female      Finance  Executive   
9985         9986      Brooke Schlesser   23  Female  Engineering     Intern   
9986         9987      Rosemarie Bernal   39  Female  Engineering    Manager   
9987         9988   Catherine Lundstrom   29  Female        Sales    Analyst   
9988         9989           Ruby Dowell   24  Female        Sales    Analyst   
9989         9990        Elaine Douglas   59  Female           HR  Executive   
9990         9991          Sally Hudson   46  Female      Finance    Manager   
9991         9992       Amanda Pariente   38  Female  Engineering    Manager   
9992         9993          Corey Medina   27    Male      Finance    Analyst   
9993         9994            Pedro Caul   51    Male      Finance  Executive   
9994         9995            Laura Ross   31  Female      Product   Engineer   
9995         9996         Thomas Rossin   51    Male        Sales  Executive   
9996         9997         Christie King   36  Female        Sales  Executive   
9997         9998         Alfred Keller   57    Male        Sales  Executive   
9998         9999        Margaret Gomez   37  Female  Engineering    Manager   
9999        10000         Joan Sorensen   25  Female        Sales    Analyst   

      Experience_Years Education_Level       Location  Salary  
9980                 0        Bachelor       New York   35000  
9981                 9        Bachelor       New York   75000  
9982                10          Master       New York  125000  
9983                 2        Bachelor  San Francisco   65000  
9984                19             PhD        Chicago  175000  
9985                 0        Bachelor         Austin   35000  
9986                16          Master       New York  140000  
9987                 8        Bachelor         Austin   80000  
9988                 3        Bachelor  San Francisco   65000  
9989                32             PhD       New York  200000  
9990                23          Master        Chicago  150000  
9991                15          Master       New York  125000  
9992                 4          Master  San Francisco   70000  
9993                28          Master       New York  200000  
9994                10        Bachelor  San Francisco   95000  
9995                28          Master         Austin  185000  
9996                 9             PhD  San Francisco  165000  
9997                30             PhD       New York  200000  
9998                14          Master       New York  135000  
9999                 4        Bachelor  San Francisco   70000

In [15]:
df.describe()

Employee_ID           Age  Experience_Years         Salary
count  10000.00000  10000.000000      10000.000000   10000.000000
mean    5000.50000     35.455900         12.370900  115381.500000
std     2886.89568     10.000213          9.148951   46066.139047
min        1.00000     21.000000          0.000000   25000.000000
25%     2500.75000     27.000000          5.000000   70000.000000
50%     5000.50000     34.000000         10.000000  120000.000000
75%     7500.25000     43.000000         19.000000  150000.000000
max    10000.00000     60.000000         37.000000  215000.000000

In [21]:
df.dropna()

Employee_ID            Name  Age  Gender   Department  Job_Title  \
0               1    Merle Ingram   24  Female  Engineering   Engineer   
1               2      John Mayes   56    Male        Sales  Executive   
2               3    Carlos Wille   21    Male  Engineering     Intern   
3               4  Michael Bryant   30    Male      Finance    Analyst   
4               5   Paula Douglas   25  Female           HR    Analyst   
...           ...             ...  ...     ...          ...        ...   
9995         9996   Thomas Rossin   51    Male        Sales  Executive   
9996         9997   Christie King   36  Female        Sales  Executive   
9997         9998   Alfred Keller   57    Male        Sales  Executive   
9998         9999  Margaret Gomez   37  Female  Engineering    Manager   
9999        10000   Joan Sorensen   25  Female        Sales    Analyst   

      Experience_Years Education_Level       Location  Salary  
0                    1          Master         Austin   90000  
1                   33          Master        Seattle  195000  
2                    1        Bachelor       New York   35000  
3                    9        Bachelor       New York   75000  
4                    2          Master        Seattle   70000  
...                ...             ...            ...     ...  
9995                28          Master         Austin  185000  
9996                 9             PhD  San Francisco  165000  
9997                30             PhD       New York  200000  
9998                14          Master       New York  135000  
9999                 4        Bachelor  San Francisco   70000  

[10000 rows x 10 columns]

In [18]:
df.fillna(35.45)

Employee_ID            Name  Age  Gender   Department  Job_Title  \
0               1    Merle Ingram   24  Female  Engineering   Engineer   
1               2      John Mayes   56    Male        Sales  Executive   
2               3    Carlos Wille   21    Male  Engineering     Intern   
3               4  Michael Bryant   30    Male      Finance    Analyst   
4               5   Paula Douglas   25  Female           HR    Analyst   
...           ...             ...  ...     ...          ...        ...   
9995         9996   Thomas Rossin   51    Male        Sales  Executive   
9996         9997   Christie King   36  Female        Sales  Executive   
9997         9998   Alfred Keller   57    Male        Sales  Executive   
9998         9999  Margaret Gomez   37  Female  Engineering    Manager   
9999        10000   Joan Sorensen   25  Female        Sales    Analyst   

      Experience_Years Education_Level       Location  Salary  
0                    1          Master         Austin   90000  
1                   33          Master        Seattle  195000  
2                    1        Bachelor       New York   35000  
3                    9        Bachelor       New York   75000  
4                    2          Master        Seattle   70000  
...                ...             ...            ...     ...  
9995                28          Master         Austin  185000  
9996                 9             PhD  San Francisco  165000  
9997                30             PhD       New York  200000  
9998                14          Master       New York  135000  
9999                 4        Bachelor  San Francisco   70000  

[10000 rows x 10 columns]

In [22]:
n=5
while n>0:
    print(n)
    n=n-1
print('blastoff')
print(n)
    

5
4
3
2
1
blastoff
0


In [24]:
while True:
    line = input('>')
    if line=='done':
        break
    print(line)
print('done!')

> hello


hello


> hey


hey


> sh


sh


> done


done!


In [25]:
while True:
    line = input('enter pass')
    if line=='alpha':
        break
    print(line)
print('accessed')

enter pass hey


hey


enter pass alpha


accessed


In [30]:
while True:
    line = input('>')
    if line[0]=='#':
        continue
    if line == 'done':
        break
    print(line)
print('done')


> hey


hey


> #hh
> done


done


In [35]:
ds = ['alpha', 'beta', 'gamma']
for friend in ds:
    print('happy new year: ', friend)
print('done!')

happy new year:  alpha
happy new year:  beta
happy new year:  gamma
done!


In [38]:
largest_so_far=-1
print('before', largest_so_far)
for the_num in [9,10,55,23,34]:
    if the_num>largest_so_far:
        largest_so_far = the_num
    print(largest_so_far, the_num)
print('after', largest_so_far)

before -1
9 9
10 10
55 55
55 23
55 34
after 55


In [42]:
zork=0
sum=0
print('before sum:', sum)
for thing in [9,41,12,3,74,15]:
    zork=zork+1
    sum+=thing
    print(zork,thing)
avg=sum/zork
print('avg',avg)
print('sum', sum)
    
    

before sum: 0
1 9
2 41
3 12
4 3
5 74
6 15
avg 25.666666666666668
sum 154


In [6]:
str1='hello'
str2='bro'
bob=str1+str2
print(bob)
str3='123'
x=int(str3)+1
print(x)
y=str3+'1'
print(y)
z=2*int(str3)
print(z)

hellobro
124
1231
246


In [7]:
a=int(input('enter a number'))
b=int(input('enter a number'))
c=a+b
print(c)


enter a number 20
enter a number 30


50


In [10]:
name=input('enter: ')
print(name)
apple=input('enter: ')
print(apple)
x=int(apple) - 1
print(x)
banana=int(input('enter: '))
print(banana)
y=banana - 1
print(y)

enter:  hey


hey


enter:  20


20
19


enter:  30


30
29


In [1]:
abc='mango'
print(abc[1])


a


In [2]:
fruit='banana'
index=0
while index<len(fruit):
    letter=fruit[index]
    print(index, letter)
    index=index+1

0 b
1 a
2 n
3 a
4 n
5 a


In [11]:
fruit='guava'
index=0
for i in fruit:
    let=fruit[index]
    print(index, let)
    index=index+1
print(len(fruit))
count=0

for i in fruit:
    if i=='a':
        count=count+1
   
    
print(count)
    
    

    


0 g
1 u
2 a
3 v
4 a
5
2


In [15]:
atr='hey python bri'
print(atr[0:4])
print(atr[4:10])
print(atr[0: ])
print(atr[ : 13])
print(atr[:])

hey 
python
hey python bri
hey python br
hey python bri


In [19]:
fruit='banana'
'n' in fruit
'm' in fruit
#if 'a' in fruit:
#print('found it!')


False

In [2]:
stuff='hello world'
dir(stuff)


['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'stri

In [4]:
import numpy as np


In [6]:
arr=np.array([1,2,3,4,5])
print(arr)
print(np.__version__)

[1 2 3 4 5]
2.3.2


In [9]:
arrr=np.array([[1,2,3],[4,5,6]])
print(arrr)


[[1 2 3]
 [4 5 6]]


In [14]:
ar=np.array(22)
arr=np.array([1,2,3,4,5])

arrr=np.array([[1,2,3],[4,5,6]])

arrrr=np.array([[[1,2,3],[7,8,9]],[[2,6,9],[4,5,6]]])
print(ar.ndim)
print(arr.ndim)
print(arrr.ndim)
print(arrrr.ndim)


0
1
2
3


In [18]:
arr=np.array([1,2,3,4], ndmin=5)
print(arr)
print('no of dimensions: ', arr.ndim)

[[[[[1 2 3 4]]]]]
no of dimensions:  5


In [20]:
arrr=np.array([[1,2,3],[4,5,6]])
print('second ele in forst row: ', arrr[0,1])

second ele in forst row:  2


In [21]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [22]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [31]:
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==7)
print(x)
arr=np.array([3,2,7,1])
print(np.sort(arr))
arr=np.array([41,42,43,44])
x=[True, False, True, False]
newarr=arr[x]
print(newarr)

(array([], dtype=int64),)
[1 2 3 7]
[41 43]
